spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/matrixed_bi?&allowMultiQueries=true
    username: matrixed_bi
    password: matrixed_bi
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lisr7ebb8NgYrZNc
            client-secret: f27de55a74cb4cf0195a583cc65d9429e1225714
            scope: read:user,user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

server:
  port: 8080
  address: 0.0.0.0

  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

datart:

  migration:
    enable: true

  server:
    address: http://127.0.0.1:8080

  user:
    active:
      send-mail: false  # 注册用户时是否需要邮件验证激活

  auth:
    oauth-auth-only: true
    word-back-to-mixed-auth: "this is admin"

  security:
    token:
      secret: "d@a$t%a^r&a*t" #加密密钥
      timeout-min: 30  # 登录会话有效时长，单位：分钟。

  env:
    file-path: ${user.dir}/files # 服务端文件保存位置

  screenshot:
    timeout-seconds: 60
    webdriver-type: CHROME
    webdriver-path: