version: '3.8'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: matrixed-bi-db
    environment:
      MYSQL_ROOT_PASSWORD: matrixed_bi
      MYSQL_DATABASE: matrixed_bi
      MYSQL_USER: matrixed_bi
      MYSQL_PASSWORD: matrixed_bi
    ports:
      - "3306:3306"
    volumes:
      - matrixed-bi-db:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  matrixed-bi-db: